---
# {{ playbook_dir }}/roles/clone-ansible-role-from-git/tasks/main.yml
- name: Clone or pull the ansible hardening repo
  git:
    repo:    '{{ git_repo_url }}'
    dest:    '{{ git_clone_dir }}'
    version: '{{ git_version }}'

- name: 'Assert that git clone of {{ git_clone_project }} role is ignored by playbook clone'
  lineinfile:
    path: '{{ playbook_dir }}/.gitignore'
    regexp: '^roles/{{ git_project }}$'
    line: 'roles/{{ git_project }}'

