---
# {{ playbook_dir }}/roles/clone-ansible-role-from-git/vars/main.yml
git_account: ''
git_project: ''
git_version: 'master'

git_baseurl: 'https://github.com'
git_repo_name: '{{ git_account }}/{{ git_project }}'
git_repo_url: '{{ git_baseurl }}/{{ git_repo_name }}.git'
git_clone_dir: '{{ playbook_dir }}/roles/{{ git_project }}'

