---
# {{ playbook_dir }}/playbook-apply.yml 
- hosts: localhost
  become: true
  roles:
    - { role: ansible-role-sudo }
    - { role: ansible-hardening }
    - { role: provide-container-engine } 
    - { role: provide-container-orchestration }
    - { role: provide-container-network-overlay }
    - { role: provide-service-mesh }
  vars_files:
    - vars/ansible-role-sudo.yml 

