---
# {{ playbook_dir }}/playbook-apply.yml 

# Should be able to use provisioner:all_nodes, but playbook doesn't load the two different group_vars correctly
- hosts: provisioner
  become: true
  roles:
    - { role: provide-container-engine } 
#    - { role: provide-web-proxy-cache }
  vars_files:
    - vars/ansible-role-docker-ce.yml 

- hosts: provisioner
  become: true
  roles:
    - { role: ansible-role-sudo }
    - { role: ansible-hardening }
  vars_files:
    - vars/ansible-role-sudo.yml
    - vars/ansible-hardening.yml

- hosts: storage
  become: true
  roles:
    - { role: ansible-role-sudo }
    - { role: ansible-hardening }
    - { role: provide-shared-file-system }
  vars_files:
    - vars/ansible-role-sudo.yml 
    - vars/ansible-hardening.yml 

- hosts: all_nodes
  become: true
  roles:
    - { role: ansible-role-sudo }
    - { role: ansible-hardening }
    - { role: provide-container-engine } 
  vars_files:
    - vars/ansible-role-sudo.yml 
    - vars/ansible-hardening.yml 
    - vars/ansible-role-docker-ce.yml 

# Should be able to use master_nodes:worker_nodes, but playbook doesn't load the two different group_vars correctly
- hosts: master_nodes
  become: true
  roles:
    - role: provide-container-orchestration 
    - role: provide-container-network-overlay 
  vars_files:
    - vars/ansible-role-kubernetes.yml 
    
- hosts: worker_nodes
  become: true
  roles:
    - role: provide-container-orchestration 
    - role: provide-container-network-overlay 
  vars_files:
    - vars/ansible-role-kubernetes.yml 
        