---
# {{ playbook_dir }}/playbook-init.yml 
- hosts: provisioner
  roles:
    - { role: clone-ansible-role-from-git, 
          git_account: 'openstack', 
          git_project: 'ansible-hardening', 
          git_version: '17.0.4' }

    - { role: clone-ansible-role-from-git, 
          git_account: 'haxorof', 
          git_project: 'ansible-role-docker-ce', 
          git_version: '1.8.0' }

    - { role: clone-ansible-role-from-git, 
          git_account: 'clusterfrak-dynamics', 
          git_project: 'symplegma-containerd', 
          git_version: 'v1.1.0' }

    - { role: clone-ansible-role-from-git, 
          git_account: 'vmware', 
          git_project: 'ansible-role-sudo', 
          git_version: 'b387a4482b2dac2640a72c512e4f232c95dc166c' }

    - { role: clone-ansible-role-from-git, 
          git_account: 'awltux', 
          git_project: 'ansible-role-kubernetes', 
          git_version: '5c4eea46ed3cc7fc9a2e3ddb2fef11e1b2fdb773' }

    - { role: clone-ansible-role-from-git, 
          git_account: 'gabethecabbage', 
          git_project: 'ansible-role-zfs', 
          git_version: '1dee2f5d8d50196af8a1abf27f6de83bf53e1b18' }

    - { role: clone-ansible-role-from-git, 
          git_account: 'awltux', 
          git_project: 'ansible-role-proxy_settings', 
          git_version: 'master' }

