---
# {{ playbook_dir }}/playbook-apply.yml 
- hosts: localhost
  become: true
  roles:
    - { role: ansible-role-sudo }
    - { role: ansible-hardening }
    - { role: provide-container-engine } 
    - { role: provide-container-manager }
    - { role: provide-container-overlay-network }
  vars_files:
    - vars/ansible-role-sudo.yml 

