---

- name: Install and configure docker
  when: container_engine == 'docker'
  block:
    - name: Include role ansible-role-docker-ce
      include_role: 
        name: ansible-role-docker-ce
       
    - name: Ensure docker service is running
      service:
        name: docker
        state: started
  
    - name: Install python docker api
      package:
        name: python-docker-py
        state: present


- name: Install and configure containerd
  include_role: 
    name: symplegma-containerd
  when: container_engine == 'containerd'

