---

- name: Create dir for squid cache and conigure SELinux
  file:
    path: /srv/docker/squid
    state: directory
    setype: svirt_sandbox_file_t
    recurse: true
    
- name: Start a squid container
  docker_container:
    name: squid
    image: sameersbn/squid:3.5.27
    state: started
    restart: yes
    restart_policy: "unless-stopped"
    ports:
      - "3128:3128"
    volumes:
      # Modified 'squid.conf' to allow localnet access.
      - "{{role_path}}/files/squid.conf:/etc/squid/squid.conf"
      - "/srv/docker/squid/cache:/var/spool/squid"