---
# {{ playbook_dir }}/roles/clone-ansible-role-from-git/tasks/main.yml
- name: "Clone or pull the {{ git_repo_name }} repo"
  git:
    repo:    '{{ git_repo_url }}'
    dest:    '{{ git_clone_dir }}'
    version: '{{ git_version }}'

- name: "Assert that git clone of {{ git_project }} role is ignored by playbook clone"
  lineinfile:
    path: '{{ playbook_dir }}/../.gitignore'
    regexp: '^ansible/roles-from-init/{{ git_project }}$'
    line: 'ansible/roles-from-init/{{ git_project }}'

